const express = require('express')
const router = express.Router()

router.use('/admin/routes', require('./admin/routes'))
router.use('/admin/bots', require('./admin/bots'))
router.use('/admin/customer-bots', require('./admin/customer-bots'))
router.use('/admin/customers', require('./admin/customers'))
router.use('/admin/emails', require('./admin/emails'))
router.use('/admin/email-errors', require('./admin/email-errors'))
router.use('/admin/event-categories', require('./admin/event-categories'))
router.use('/admin/events', require('./admin/events'))
router.use('/admin/event-occurrences', require('./admin/event-occurrences'))
router.use('/admin/event-prices', require('./admin/event-prices'))
router.use('/admin/faqs', require('./admin/faqs'))
router.use('/admin/faqs-items', require('./admin/faqs-items'))
router.use('/admin/images', require('./admin/images'))
router.use('/admin/languages', require('./admin/languages'))
router.use('/admin/promoters', require('./admin/promoters'))
router.use('/admin/promoter-spots', require('./admin/promoter-spots'))
router.use('/admin/sent-emails', require('./admin/sent-emails'))
router.use('/admin/spots', require('./admin/spots'))
router.use('/admin/towns', require('./admin/towns'))
router.use('/admin/users', require('./admin/users'))
router.use('/admin/menus', require('./admin/menus'))
router.use('/admin/menu-items', require('./admin/menu-items'))
router.use('/admin/locale-seos', require('./admin/locale-seos'))
router.use('/admin/heroes', require('./admin/heroes'))
router.use('/admin/cards', require('./admin/cards'))
router.use('/admin/cards-items', require('./admin/cards-items'))
router.use('/admin/feature-titles', require('./admin/feature-titles'))
router.use('/admin/feature-title-items', require('./admin/feature-title-items'))
router.use('/customer/images', require('./customer/images'))
router.use('/customer/faqs', require('./customer/faqs'))
router.use('/customer/feature-titles', require('./customer/feature-titles'))
router.use('/customer/heroes', require('./customer/heroes'))
router.use('/customer/cards', require('./customer/cards'))
router.use('/customer/chats', require('./customer/chats'))

module.exports = router
